WebAppPortefolio/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppPortefolio.Data;

namespace WebAppPortefolio.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(
        int maxPriority, bool isDone)
        {
            return View();
        }
    }
}

WebAppPortefolio/ViewComponents/TopbarViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppPortefolio.Data;
using WebAppPortefolio.Models;

namespace WebAppPortefolio.ViewComponents
{
    public class TopbarViewComponent : ViewComponent
    {
        private IHttpContextAccessor _accessor;

        public TopbarViewComponent(IHttpContextAccessor accessor)
        {
            _accessor = accessor;
        }

        public IViewComponentResult Invoke(
        int maxPriority, bool isDone)
        {
            DbContextOptions<PortefolioContext> _options = new DbContextOptions<PortefolioContext>();
            var db = new PortefolioContext(_options);

            //Inicializar ome do utilizador
            ViewBag.NomeDele = "Sem Utilizador";

            if (User.Identity.IsAuthenticated)
            {
                Utilizador _u = db.Utilizadores.Where(ut => ut.Email == HttpContext.User.Identity.Name).FirstOrDefault();

                if(_u != null)
                    ViewBag.NomeDele = _u.Nome;
            }            

            return View();
        }               
    }
}

WebAppPortefolio/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Carbon - Admin Template</title>
    <link rel="stylesheet" href="~/dist/vendor/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="~/dist/vendor/font-awesome/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/dist/css/styles.css">
</head>
<body class="sidebar-fixed header-fixed">
    <div class="page-wrapper">

        <!-- Top Bar -->
        @await Component.InvokeAsync("Topbar")
        <!-- #Top Bar -->
        <!-- #Side Bar -->
        @await Component.InvokeAsync("Sidebar")
        <!-- #Side Bar -->

        <div class="content" style="background-color:#D3D3D3">
            @RenderBody()
        </div>

    </div>

    <script src="~/dist/vendor/jquery/jquery.min.js"></script>
    <script src="~/dist/vendor/popper.js/popper.min.js"></script>
    <script src="~/dist/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/dist/vendor/chart.js/chart.min.js"></script>
    <script src="~/src/js/carbon.js"></script>
    <script src="~/src/js/demo.js"></script>

    <!-- Notificações -->
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>